.PHONY: clean All

All:
	@echo "----------Building project:[ C_Mini_Projekt - Debug ]----------"
	@"$(MAKE)" -f  "C_Mini_Projekt.mk"
clean:
	@echo "----------Cleaning project:[ C_Mini_Projekt - Debug ]----------"
	@"$(MAKE)" -f  "C_Mini_Projekt.mk" clean
